services:
  tomcat:
    build: .
    container_name: library_tomcat
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=1433
      - DB_NAME=library_system
      - DB_USER=sa
      - DB_PASSWORD=12345
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./logs:/usr/local/tomcat/logs
    networks:
      - app-network

  nginx:
    image: nginx:1.25.5
    container_name: library_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tomcat
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge